package apc.model;
// Generated 18/09/2018 08:17:12 PM by Hibernate Tools 4.3.1


import apc.bean.facturaBean;
import java.math.BigDecimal;

/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private Integer codDetalle;
     private Factura factura;
     private Producto producto;
     private String codBarra;
     private String nombreProducto;
     private int cantidad;
     private float precioVenta;
     private float total;

    public Detallefactura() {
    }

    public Detallefactura(Factura factura, Producto producto, String codBarra, String nombreProducto, int cantidad, 
            float precioVenta, float total) {
       this.factura = factura;
       this.producto = producto;
       this.codBarra = codBarra;
       this.nombreProducto = nombreProducto;
       this.cantidad = cantidad;
       this.precioVenta = precioVenta;
       this.total = total;    }

    public Detallefactura(Object object, Object object0, facturaBean aThis, String codBarra, Integer codProducto, int i, float precioVenta, BigDecimal bigDecimal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    }
   
    public Integer getCodDetalle() {
        return this.codDetalle;
    }
    
    public void setCodDetalle(Integer codDetalle) {
        this.codDetalle = codDetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getCodBarra() {
        return this.codBarra;
    }
    
    public void setCodBarra(String codBarra) {
        this.codBarra = codBarra;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public float getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(float precioVenta) {
        this.precioVenta = precioVenta;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }




}


